// 데일리 타로 카드 데이터 (웹)
// onecard 커스텀 덱에서 변환. 타로 78장 + 오라클 35장.
// description은 onecard 앱의 고정 해석 그대로이며, DailyTarot 화면에서
// 이 텍스트를 그대로 노출한다. (AI 호출 없음 — 2026-07-02)

export const TAROT_CARDS = [
  {
    "id": "major_0",
    "nameKo": "The Fool",
    "nameEn": "The Fool",
    "keywords": "새로운 시작, 모험, 순수함, 잠재력",
    "keywordsEn": "New beginnings, adventure, innocence, potential",
    "description": "오늘은 새로운 시작과 무한한 가능성으로 가득 찬 하루입니다. 예상치 못한 제안이나 기회가 찾아올 수 있어요. 때로는 계획 없이 즉흥적으로 내딛는 첫걸음이 더 큰 행운을 가져다줄 수 있습니다. 마음의 소리에 귀 기울여 보세요.",
    "image": "/assets/tarot/major_0.png",
    "isPositive": true,
    "score": 50,
    "deck": "tarot"
  },
  {
    "id": "major_1",
    "nameKo": "The Magician",
    "nameEn": "The Magician",
    "keywords": "창의력, 재능, 자신감, 실행력",
    "keywordsEn": "Creativity, talent, confidence, action",
    "description": "오늘은 당신의 재능과 창의력을 마음껏 발휘할 수 있는 하루입니다. 무엇이든 가능하게 만드는 자신감과 능력이 넘칩니다. 새로운 아이디어를 실행에 옮기거나 목표를 향해 나아가기에 완벽한 날이에요.",
    "image": "/assets/tarot/major_1.png",
    "isPositive": true,
    "score": 85,
    "deck": "tarot"
  },
  {
    "id": "major_2",
    "nameKo": "The High Priestess",
    "nameEn": "The High Priestess",
    "keywords": "직관, 통찰력, 지혜, 비밀",
    "keywordsEn": "Intuition, insight, wisdom, mystery",
    "description": "오늘은 논리보다 직감을 믿어야 하는 하루입니다. 서두르기보다 차분히 내면의 목소리에 귀를 기울여보세요. 숨겨져 있던 진실을 발견하거나 중요한 통찰을 얻게 될 수 있습니다.",
    "image": "/assets/tarot/major_2.png",
    "isPositive": true,
    "score": 75,
    "deck": "tarot"
  },
  {
    "id": "major_3",
    "nameKo": "The Empress",
    "nameEn": "The Empress",
    "keywords": "풍요, 결실, 다산, 안정",
    "keywordsEn": "Abundance, fruition, prosperity, stability",
    "description": "풍요와 창조의 에너지가 가득한 하루입니다. 진행 중인 일이 결실을 보고, 관계에서는 사랑과 만족을 느낄 수 있습니다. 물질적으로나 감정적으로 모두 풍요로운 날이 될 거예요.",
    "image": "/assets/tarot/major_3.png",
    "isPositive": true,
    "score": 80,
    "deck": "tarot"
  },
  {
    "id": "major_4",
    "nameKo": "The Emperor",
    "nameEn": "The Emperor",
    "keywords": "권위적인, 통제, 고집, 책임감",
    "keywordsEn": "Authority, control, stubbornness, responsibility",
    "description": "오늘은 지나치게 권위적이거나 고지식한 태도로 인해 갈등이 생길 수 있는 하루입니다. 자신의 방식만을 고집하기보다 주변 사람들의 의견에 귀를 기울이고 유연한 자세를 보이는 것이 중요합니다. 책임감은 좋지만, 통제가 아닌 조화를 추구하세요.",
    "image": "/assets/tarot/major_4.png",
    "isPositive": false,
    "score": 30,
    "deck": "tarot"
  },
  {
    "id": "major_5",
    "nameKo": "The Hierophant",
    "nameEn": "The Hierophant",
    "keywords": "전통, 관습, 규칙, 보수적",
    "keywordsEn": "Tradition, custom, rule, conservative",
    "description": "오늘은 규칙이나 전통에 얽매여 답답함을 느낄 수 있는 하루입니다. 정해진 틀에서 벗어나기 어려워 새로운 시도를 망설이게 될 수 있어요. 때로는 자신만의 신념을 따르는 용기가 필요합니다.",
    "image": "/assets/tarot/major_5.png",
    "isPositive": false,
    "score": 25,
    "deck": "tarot"
  },
  {
    "id": "major_6",
    "nameKo": "The Lovers",
    "nameEn": "The Lovers",
    "keywords": "사랑, 관계, 조화, 선택",
    "keywordsEn": "Love, relationship, harmony, choice",
    "description": "사랑과 관계의 기쁨이 가득한 하루입니다. 중요한 선택의 기로에 놓일 수도 있습니다. 당신의 마음이 이끄는 대로, 가치관에 따라 결정한다면 최고의 결과를 얻을 수 있을 거예요.",
    "image": "/assets/tarot/major_6.png",
    "isPositive": true,
    "score": 90,
    "deck": "tarot"
  },
  {
    "id": "major_7",
    "nameKo": "The Chariot",
    "nameEn": "The Chariot",
    "keywords": "승리, 추진력, 의지, 목표 달성",
    "keywordsEn": "Victory, determination, will, goal achievement",
    "description": "오늘은 목표를 향해 힘차게 돌진해야 하는 하루입니다. 강한 의지와 자신감으로 무장한다면 어떤 어려움도 극복하고 승리를 쟁취할 수 있습니다. 망설이지 말고 앞으로 나아가세요.",
    "image": "/assets/tarot/major_7.png",
    "isPositive": true,
    "score": 70,
    "deck": "tarot"
  },
  {
    "id": "major_8",
    "nameKo": "Strength",
    "nameEn": "Strength",
    "keywords": "내면의 힘, 용기, 인내, 부드러운 카리스마",
    "keywordsEn": "Inner strength, courage, patience, gentle charisma",
    "description": "오늘은 부드러움이 강함을 이기는 내면의 힘을 발휘할 날입니다. 어려운 상황일수록 인내심을 갖고 차분하게 대처하세요. 당신의 용기와 부드러운 카리스마가 모든 것을 해결해 줄 것입니다.",
    "image": "/assets/tarot/major_8.png",
    "isPositive": true,
    "score": 65,
    "deck": "tarot"
  },
  {
    "id": "major_9",
    "nameKo": "The Hermit",
    "nameEn": "The Hermit",
    "keywords": "내면 성찰, 지혜 탐구, 재충전, 혼자만의 시간",
    "keywordsEn": "Inner reflection, wisdom exploration, recharge, alone time",
    "description": "오늘은 잠시 세상의 소음에서 벗어나 혼자만의 시간을 가지며 내면을 성찰하기 좋은 하루입니다. 해결되지 않는 문제가 있다면, 외부에서 답을 찾기보다 조용히 자기 자신에게 집중할 때 해답을 얻을 수 있습니다.",
    "image": "/assets/tarot/major_9.png",
    "isPositive": false,
    "score": 20,
    "deck": "tarot"
  },
  {
    "id": "major_10",
    "nameKo": "Wheel of Fortune",
    "nameEn": "Wheel of Fortune",
    "keywords": "운명적 전환, 행운, 기회, 변화",
    "keywordsEn": "Destructive transition, fortune, opportunity, change",
    "description": "예상치 못한 행운과 긍정적인 변화가 찾아오는 하루입니다. 운명의 수레바퀴가 당신에게 유리한 방향으로 움직이기 시작했어요. 새로운 기회를 두려워 말고 적극적으로 받아들이세요.",
    "image": "/assets/tarot/major_10.png",
    "isPositive": true,
    "score": 75,
    "deck": "tarot"
  },
  {
    "id": "major_11",
    "nameKo": "Justice",
    "nameEn": "Justice",
    "keywords": "정의, 균형, 공정함, 책임",
    "keywordsEn": "Justice, balance, fairness, responsibility",
    "description": "공정하고 현명한 판단이 필요한 하루입니다. 중요한 결정을 내려야 한다면, 감정에 치우치지 말고 객관적인 시각을 유지하세요. 당신의 행동에 대한 정당한 결과를 얻게 될 것입니다.",
    "image": "/assets/tarot/major_11.png",
    "isPositive": true,
    "score": 80,
    "deck": "tarot"
  },
  {
    "id": "major_12",
    "nameKo": "The Hanged Man",
    "nameEn": "The Hanged Man",
    "keywords": "인내, 희생, 정체, 새로운 관점",
    "keywordsEn": "Patience, sacrifice, stagnation, new perspective",
    "description": "오늘은 상황이 뜻대로 풀리지 않고 정체된 느낌을 받을 수 있습니다. 하지만 이는 더 큰 깨달음을 얻기 위한 인내의 과정입니다. 다른 관점에서 문제를 바라보는 노력이 필요한 하루입니다.",
    "image": "/assets/tarot/major_12.png",
    "isPositive": false,
    "score": 15,
    "deck": "tarot"
  },
  {
    "id": "major_13",
    "nameKo": "Death",
    "nameEn": "Death",
    "keywords": "끝, 변화, 이별, 새로운 시작",
    "keywordsEn": "End, change, separation, new beginning",
    "description": "오늘은 어떤 상황의 끝과 새로운 시작을 동시에 맞이하는 하루입니다. 과거의 것을 과감히 정리해야 더 나은 미래로 나아갈 수 있습니다. 변화는 고통스럽지만, 꼭 필요한 과정임을 기억하세요.",
    "image": "/assets/tarot/major_13.png",
    "isPositive": false,
    "score": 10,
    "deck": "tarot"
  },
  {
    "id": "major_14",
    "nameKo": "Temperance",
    "nameEn": "Temperance",
    "keywords": "조화, 균형, 절제, 인내",
    "keywordsEn": "Harmony, balance, moderation, patience",
    "description": "오늘은 조화와 균형을 찾는 것이 중요한 하루입니다. 사람들과의 관계나 일 처리에서 극단에 치우치지 않고 중용의 미덕을 발휘하세요. 인내심을 갖고 상황을 조율한다면 평화를 찾을 수 있습니다.",
    "image": "/assets/tarot/major_14.png",
    "isPositive": true,
    "score": 70,
    "deck": "tarot"
  },
  {
    "id": "major_15",
    "nameKo": "The Devil",
    "nameEn": "The Devil",
    "keywords": "유혹, 집착, 중독, 속박",
    "keywordsEn": "Temptation, obsession, addiction, bondage",
    "description": "오늘은 물질적 유혹이나 부정적인 관계에 얽매일 수 있는 하루입니다. 벗어나고 싶지만 벗어날 수 없는 중독적인 상황에 빠지지 않도록 주의하세요. 자신의 욕망을 솔직하게 들여다볼 필요가 있습니다.",
    "image": "/assets/tarot/major_15.png",
    "isPositive": false,
    "score": 5,
    "deck": "tarot"
  },
  {
    "id": "major_16",
    "nameKo": "The Tower",
    "nameEn": "The Tower",
    "keywords": "급작스러운 변화, 충격, 파괴, 각성",
    "keywordsEn": "Unexpected change, shock, destruction, awakening",
    "description": "예상치 못한 충격적인 사건으로 인해 기존의 질서가 무너질 수 있는 하루입니다. 혼란스럽고 힘들겠지만, 이 변화는 당신을 더 단단하게 만들고 새로운 시작을 위한 기반이 될 것입니다.",
    "image": "/assets/tarot/major_16.png",
    "isPositive": false,
    "score": 20,
    "deck": "tarot"
  },
  {
    "id": "major_17",
    "nameKo": "The Star",
    "nameEn": "The Star",
    "keywords": "희망, 영감, 긍정, 치유",
    "keywordsEn": "Hope, inspiration, positivity, healing",
    "description": "희망과 영감이 샘솟는 긍정적인 하루입니다. 어려운 상황 속에서도 미래에 대한 밝은 비전을 발견하게 될 거예요. 당신의 꿈과 이상을 믿고 나아가세요. 좋은 기운이 함께합니다.",
    "image": "/assets/tarot/major_17.png",
    "isPositive": true,
    "score": 85,
    "deck": "tarot"
  },
  {
    "id": "major_18",
    "nameKo": "The Moon",
    "nameEn": "The Moon",
    "keywords": "불안, 혼란, 환상, 두려움",
    "keywordsEn": "Anxiety, confusion, illusion, fear",
    "description": "오늘은 불안감과 혼란스러움으로 인해 방향을 잃기 쉬운 하루입니다. 현실과 환상을 구분하기 어려울 수 있으니, 중요한 결정은 피하는 것이 좋습니다. 내면의 두려움을 마주할 용기가 필요합니다.",
    "image": "/assets/tarot/major_18.png",
    "isPositive": false,
    "score": 30,
    "deck": "tarot"
  },
  {
    "id": "major_19",
    "nameKo": "The Sun",
    "nameEn": "The Sun",
    "keywords": "성공, 행복, 긍정, 활력",
    "keywordsEn": "Success, happiness, positivity, vitality",
    "description": "성공과 행복의 에너지가 가득한 최고의 하루입니다. 모든 일이 긍정적으로 풀리고, 자신감과 활력이 넘칩니다. 주변 사람들과의 관계도 좋아지니, 이 좋은 기운을 마음껏 즐기세요.",
    "image": "/assets/tarot/major_19.png",
    "isPositive": true,
    "score": 90,
    "deck": "tarot"
  },
  {
    "id": "major_20",
    "nameKo": "Judgement",
    "nameEn": "Judgement",
    "keywords": "부활, 보상, 새로운 소명, 용서",
    "keywordsEn": "Resurrection, reward, new calling, forgiveness",
    "description": "과거의 노력에 대한 보상을 받고 새로운 부름에 응답해야 하는 하루입니다. 중요한 결정을 통해 한 단계 더 성장하게 될 것입니다. 과거를 용서하고 새로운 시작을 받아들이세요.",
    "image": "/assets/tarot/major_20.png",
    "isPositive": true,
    "score": 80,
    "deck": "tarot"
  },
  {
    "id": "major_21",
    "nameKo": "The World",
    "nameEn": "The World",
    "keywords": "완성, 성취, 성공, 새로운 단계",
    "keywordsEn": "Completion, achievement, success, new stage",
    "description": "오랫동안 노력해온 일이 드디어 완성되고 큰 성취감을 맛보는 하루입니다. 성공적인 마무리와 함께 새로운 세상으로 나아갈 준비가 되었습니다. 만족감과 행복을 만끽하세요.",
    "image": "/assets/tarot/major_21.png",
    "isPositive": true,
    "score": 95,
    "deck": "tarot"
  },
  {
    "id": "ace_cups",
    "nameKo": "Ace of Cups",
    "nameEn": "Ace of Cups",
    "keywords": "새로운 감정, 사랑의 시작, 공감, 행복",
    "keywordsEn": "New emotions, beginning of love, empathy, happiness",
    "description": "오늘은 새로운 사랑이나 감정이 싹트는 하루입니다. 마음이 열리고, 사람들과 깊은 감정적 교류를 나눌 수 있습니다. 창의적인 영감이 넘치고, 행복한 감정을 만끽하게 될 거예요.",
    "image": "/assets/tarot/ace_cups.png",
    "isPositive": true,
    "score": 85,
    "deck": "tarot"
  },
  {
    "id": "cups_2",
    "nameKo": "Two of Cups",
    "nameEn": "Two of Cups",
    "keywords": "연합, 파트너십, 사랑, 교감",
    "keywordsEn": "Union, partnership, love, connection",
    "description": "오늘은 사랑하는 사람이나 파트너와 깊은 교감을 나누는 조화로운 하루입니다. 서로의 마음을 확인하고 관계가 한 단계 더 발전할 수 있습니다. 새로운 인연을 만나기에도 좋은 날입니다.",
    "image": "/assets/tarot/cups_2.png",
    "isPositive": true,
    "score": 80,
    "deck": "tarot"
  },
  {
    "id": "cups_3",
    "nameKo": "Three of Cups",
    "nameEn": "Three of Cups",
    "keywords": "축하, 우정, 즐거운 모임, 기쁨",
    "keywordsEn": "Celebration, friendship, enjoyable gathering, joy",
    "description": "친구들과 함께 기쁨을 나누고 축하할 일이 생기는 즐거운 하루입니다. 사교적인 모임이나 파티에서 즐거운 시간을 보내게 될 수 있습니다. 함께하는 것의 행복을 느껴보세요.",
    "image": "/assets/tarot/cups_3.png",
    "isPositive": true,
    "score": 75,
    "deck": "tarot"
  },
  {
    "id": "cups_4",
    "nameKo": "Four of Cups",
    "nameEn": "Four of Cups",
    "keywords": "권태, 무관심, 불만족, 기회를 놓침",
    "keywordsEn": "Apathy, indifference, dissatisfaction, missing opportunity",
    "description": "오늘은 일상에 대한 권태감이나 무기력함을 느낄 수 있는 하루입니다. 주변에서 주어지는 좋은 기회나 제안을 알아차리지 못하고 지나칠 수 있어요. 새로운 관점으로 주변을 둘러보는 노력이 필요합니다.",
    "image": "/assets/tarot/cups_4.png",
    "isPositive": false,
    "score": 40,
    "deck": "tarot"
  },
  {
    "id": "cups_5",
    "nameKo": "Five of Cups",
    "nameEn": "Five of Cups",
    "keywords": "상실, 후회, 슬픔, 실망",
    "keywordsEn": "Loss, regret, sadness, disappointment",
    "description": "과거의 상실감이나 후회에 얽매여 슬픔을 느낄 수 있는 하루입니다. 잃어버린 것에만 집중하기보다, 아직 당신에게 남아있는 소중한 것들을 돌아보세요. 긍정적인 면을 보려는 노력이 필요합니다.",
    "image": "/assets/tarot/cups_5.png",
    "isPositive": false,
    "score": 25,
    "deck": "tarot"
  },
  {
    "id": "cups_6",
    "nameKo": "Six of Cups",
    "nameEn": "Six of Cups",
    "keywords": "추억, 순수함, 그리움, 옛 친구",
    "keywordsEn": "Memories, purity, homesickness, old friend",
    "description": "과거의 좋은 추억이나 오랜 친구에게서 행복을 느끼는 하루입니다. 순수했던 시절을 떠올리게 하는 일이 생기거나, 반가운 사람에게서 연락이 올 수 있습니다. 따뜻한 감정을 나눠보세요.",
    "image": "/assets/tarot/cups_6.png",
    "isPositive": true,
    "score": 70,
    "deck": "tarot"
  },
  {
    "id": "cups_7",
    "nameKo": "Seven of Cups",
    "nameEn": "Seven of Cups",
    "keywords": "환상, 비현실적 기대, 선택의 어려움, 혼란",
    "keywordsEn": "Fantasy, unrealistic expectations, difficulty in choice, confusion",
    "description": "오늘은 너무 많은 선택지와 비현실적인 환상 속에서 길을 잃기 쉬운 하루입니다. 허황된 꿈보다는 현실에 집중하고, 정말로 원하는 것이 무엇인지 명확히 해야 할 필요가 있습니다.",
    "image": "/assets/tarot/cups_7.png",
    "isPositive": false,
    "score": 35,
    "deck": "tarot"
  },
  {
    "id": "cups_8",
    "nameKo": "Eight of Cups",
    "nameEn": "Eight of Cups",
    "keywords": "떠남, 전환, 새로운 길 모색, 미련 버리기",
    "keywordsEn": "Leaving, transition, exploring new paths, letting go of regret",
    "description": "오늘은 더 이상 만족을 주지 못하는 상황이나 관계를 뒤로하고 떠나야 할 수 있는 하루입니다. 새로운 시작을 위해 현재의 안정을 포기하는 용기가 필요합니다. 더 나은 것을 찾아 떠나세요.",
    "image": "/assets/tarot/cups_8.png",
    "isPositive": false,
    "score": 30,
    "deck": "tarot"
  },
  {
    "id": "cups_9",
    "nameKo": "Nine of Cups",
    "nameEn": "Nine of Cups",
    "keywords": "소원 성취, 만족, 행복, 풍요",
    "keywordsEn": "Wish fulfillment, satisfaction, happiness, abundance",
    "description": "바라던 소원이 이루어지는 만족스러운 하루입니다. 물질적으로나 감정적으로 큰 만족감과 행복을 느끼게 될 것입니다. 당신의 성과를 마음껏 즐기고 스스로를 칭찬해주세요.",
    "image": "/assets/tarot/cups_9.png",
    "isPositive": true,
    "score": 85,
    "deck": "tarot"
  },
  {
    "id": "cups_10",
    "nameKo": "Ten of Cups",
    "nameEn": "Ten of Cups",
    "keywords": "가정의 행복, 완전한 사랑, 조화, 정서적 만족",
    "keywordsEn": "Family happiness, perfect love, harmony, emotional satisfaction",
    "description": "가족이나 사랑하는 사람들과 함께 완벽한 행복과 조화를 누리는 하루입니다. 감정적인 충만함과 안정감을 느끼며, 모든 관계에서 사랑과 기쁨이 넘쳐날 것입니다.",
    "image": "/assets/tarot/cups_10.png",
    "isPositive": true,
    "score": 90,
    "deck": "tarot"
  },
  {
    "id": "ace_pentacles",
    "nameKo": "Ace of Pentacles",
    "nameEn": "Ace of Pentacles",
    "keywords": "새로운 기회, 번영, 안정, 현실화",
    "keywordsEn": "New opportunity, prosperity, stability, reality",
    "description": "오늘은 새로운 사업 기회나 금전적 행운의 씨앗이 심어지는 하루입니다. 현실적인 계획을 세우고 실행에 옮기기 좋은 날입니다. 당신의 노력이 구체적인 결실로 이어질 것입니다.",
    "image": "/assets/tarot/ace_pentacles.png",
    "isPositive": true,
    "score": 80,
    "deck": "tarot"
  },
  {
    "id": "pentacle_2",
    "nameKo": "Two of Pentacles",
    "nameEn": "Two of Pentacles",
    "keywords": "균형, 유연성, 적응, 변화 관리",
    "keywordsEn": "Balance, flexibility, adaptability, change management",
    "description": "오늘은 여러 가지 일을 동시에 처리하며 바쁘게 움직이는 하루가 될 수 있습니다. 변화하는 상황에 유연하게 대처하고 균형을 잘 잡는 능력이 중요합니다. 즐거운 마음으로 변화에 적응하세요.",
    "image": "/assets/tarot/pentacle_2.png",
    "isPositive": true,
    "score": 65,
    "deck": "tarot"
  },
  {
    "id": "pentacle_3",
    "nameKo": "Three of Pentacles",
    "nameEn": "Three of Pentacles",
    "keywords": "팀워크, 협력, 기술, 인정",
    "keywordsEn": "Teamwork, cooperation, skills, recognition",
    "description": "오늘은 다른 사람들과의 협력을 통해 뛰어난 결과를 만들어내는 하루입니다. 당신의 기술과 재능을 인정받고, 팀워크를 통해 더 크게 성장할 수 있는 기회가 찾아옵니다.",
    "image": "/assets/tarot/pentacle_3.png",
    "isPositive": true,
    "score": 70,
    "deck": "tarot"
  },
  {
    "id": "pentacle_4",
    "nameKo": "Four of Pentacles",
    "nameEn": "Four of Pentacles",
    "keywords": "소유, 안정, 보수적, 절약",
    "keywordsEn": "Ownership, stability, conservatism, frugality",
    "description": "물질적인 안정과 성과를 지키려는 마음이 강해지는 하루입니다. 안정감을 느끼는 것은 좋지만, 지나치게 인색하거나 변화를 두려워하는 태도는 경계해야 합니다. 때로는 베푸는 것이 더 큰 이득을 가져옵니다.",
    "image": "/assets/tarot/pentacle_4.png",
    "isPositive": true,
    "score": 75,
    "deck": "tarot"
  },
  {
    "id": "pentacle_5",
    "nameKo": "Five of Pentacles",
    "nameEn": "Five of Pentacles",
    "keywords": "재정적 어려움, 고립, 상실감, 역경",
    "keywordsEn": "Financial difficulties, isolation, sense of loss, adversity",
    "description": "금전적인 어려움이나 소외감으로 인해 힘든 하루가 될 수 있습니다. 혼자 모든 것을 짊어지려 하지 말고, 주변에 도움을 요청하는 용기를 내세요. 가까운 곳에 당신을 도울 사람이 있습니다.",
    "image": "/assets/tarot/pentacle_5.png",
    "isPositive": false,
    "score": 30,
    "deck": "tarot"
  },
  {
    "id": "pentacle_6",
    "nameKo": "Six of Pentacles",
    "nameEn": "Six of Pentacles",
    "keywords": "나눔, 관대함, 도움, 보상",
    "keywordsEn": "Generosity, generosity, help, reward",
    "description": "오늘은 도움을 주거나 받으며 나눔의 기쁨을 느끼는 하루입니다. 금전적인 흐름이 원활해지고, 관대함을 베풀수록 더 큰 보상이 따릅니다. 공정하고 균형 잡힌 관계를 유지하세요.",
    "image": "/assets/tarot/pentacle_6.png",
    "isPositive": true,
    "score": 80,
    "deck": "tarot"
  },
  {
    "id": "pentacle_7",
    "nameKo": "Seven of Pentacles",
    "nameEn": "Seven of Pentacles",
    "keywords": "인내, 평가, 기다림, 투자",
    "keywordsEn": "Patience, evaluation, waiting, investment",
    "description": "그동안의 노력을 되돌아보며 수확을 기다리는 하루입니다. 아직 결과가 보이지 않더라도 실망하지 마세요. 인내심을 갖고 꾸준히 나아간다면 머지않아 풍성한 결실을 맺게 될 것입니다.",
    "image": "/assets/tarot/pentacle_7.png",
    "isPositive": true,
    "score": 70,
    "deck": "tarot"
  },
  {
    "id": "pentacle_8",
    "nameKo": "Eight of Pentacles",
    "nameEn": "Eight of Pentacles",
    "keywords": "숙련, 장인정신, 노력, 집중",
    "keywordsEn": "Expertise, craftsmanship, effort, concentration",
    "description": "자신의 일에 몰두하여 기술을 연마하고 전문성을 키우기 좋은 하루입니다. 꾸준하고 성실한 노력이 당신을 전문가의 반열에 올려놓을 것입니다. 배움과 성장에 집중하세요.",
    "image": "/assets/tarot/pentacle_8.png",
    "isPositive": true,
    "score": 75,
    "deck": "tarot"
  },
  {
    "id": "pentacle_9",
    "nameKo": "Nine of Pentacles",
    "nameEn": "Nine of Pentacles",
    "keywords": "독립, 풍요, 자수성가, 여유",
    "keywordsEn": "Independence, abundance, self-sufficiency, freedom",
    "description": "스스로의 노력으로 이룬 풍요와 성공을 만끽하는 하루입니다. 경제적, 정신적으로 독립하여 여유를 즐길 수 있습니다. 자신감과 만족감이 넘치는 하루를 보내세요.",
    "image": "/assets/tarot/pentacle_9.png",
    "isPositive": true,
    "score": 85,
    "deck": "tarot"
  },
  {
    "id": "pentacle_10",
    "nameKo": "Ten of Pentacles",
    "nameEn": "Ten of Pentacles",
    "keywords": "부, 유산, 가족의 번영, 안정",
    "keywordsEn": "Wealth, inheritance, family prosperity, stability",
    "description": "물질적 풍요와 가족의 안정이 함께하는 풍요로운 하루입니다. 그동안 쌓아온 부와 명성을 가족, 공동체와 함께 나누며 큰 행복을 느끼게 될 것입니다. 안정된 기반 위에서 미래를 계획하세요.",
    "image": "/assets/tarot/pentacle_10.png",
    "isPositive": true,
    "score": 90,
    "deck": "tarot"
  },
  {
    "id": "ace_swords",
    "nameKo": "Ace of Swords",
    "nameEn": "Ace of Swords",
    "keywords": "명확함, 진실, 돌파구, 이성적 판단",
    "keywordsEn": "Clarity, truth, breakthrough, rational judgment",
    "description": "오늘은 명쾌한 아이디어가 떠오르고 진실을 꿰뚫어 보는 하루입니다. 복잡했던 문제가 명확해지고, 이성적인 판단으로 올바른 결정을 내릴 수 있습니다. 새로운 도전을 시작하기에 좋은 날입니다.",
    "image": "/assets/tarot/ace_swords.png",
    "isPositive": true,
    "score": 75,
    "deck": "tarot"
  },
  {
    "id": "swords_2",
    "nameKo": "Two of Swords",
    "nameEn": "Two of Swords",
    "keywords": "결정 장애, 교착 상태, 갈등, 외면",
    "keywordsEn": "Decision-making difficulty, deadlock, conflict, avoidance",
    "description": "이러지도 저러지도 못하는 진퇴양난의 상황에서 결정을 내리기 어려운 하루입니다. 일부러 진실을 외면하고 있을 수도 있습니다. 마음의 눈을 뜨고 상황을 직시해야 할 필요가 있습니다.",
    "image": "/assets/tarot/swords_2.png",
    "isPositive": false,
    "score": 45,
    "deck": "tarot"
  },
  {
    "id": "swords_3",
    "nameKo": "Three of Swords",
    "nameEn": "Three of Swords",
    "keywords": "상심, 슬픔, 고통스러운 진실, 이별",
    "keywordsEn": "Heartache, sadness, painful truth, separation",
    "description": "가슴 아픈 진실을 마주하거나 상처받는 말을 듣게 될 수 있는 하루입니다. 슬프고 고통스럽겠지만, 이 아픔을 있는 그대로 받아들이는 것이 치유의 첫걸음입니다.",
    "image": "/assets/tarot/swords_3.png",
    "isPositive": false,
    "score": 20,
    "deck": "tarot"
  },
  {
    "id": "swords_4",
    "nameKo": "Four of Swords",
    "nameEn": "Four of Swords",
    "keywords": "휴식, 재충전, 회복, 평화",
    "keywordsEn": "Rest, recharge, recovery, peace",
    "description": "오늘은 모든 것을 잠시 멈추고 휴식을 취해야 하는 하루입니다. 스트레스와 갈등에서 벗어나 재충전의 시간을 가지세요. 이 휴식은 다음 단계를 위한 중요한 준비 과정입니다.",
    "image": "/assets/tarot/swords_4.png",
    "isPositive": false,
    "score": 35,
    "deck": "tarot"
  },
  {
    "id": "swords_5",
    "nameKo": "Five of Swords",
    "nameEn": "Five of Swords",
    "keywords": "갈등, 패배, 불명예, 이기적인 승리",
    "keywordsEn": "Conflict, defeat, dishonor, selfish victory",
    "description": "이기더라도 상처만 남는 불필요한 갈등이나 경쟁에 휘말릴 수 있는 하루입니다. 자존심을 내세우기보다 한발 물러서는 것이 현명합니다. 승리보다 중요한 것이 무엇인지 생각해보세요.",
    "image": "/assets/tarot/swords_5.png",
    "isPositive": false,
    "score": 25,
    "deck": "tarot"
  },
  {
    "id": "swords_6",
    "nameKo": "Six of Swords",
    "nameEn": "Six of Swords",
    "keywords": "전환, 이동, 회복, 새로운 시작",
    "keywordsEn": "Transition, movement, recovery, new beginning",
    "description": "어려운 상황에서 벗어나 더 나은 곳으로 나아가는 전환의 하루입니다. 힘든 시기가 끝나고 평온한 미래가 기다리고 있습니다. 논리적인 조언자의 도움을 받을 수도 있습니다.",
    "image": "/assets/tarot/swords_6.png",
    "isPositive": true,
    "score": 70,
    "deck": "tarot"
  },
  {
    "id": "swords_7",
    "nameKo": "Seven of Swords",
    "nameEn": "Seven of Swords",
    "keywords": "기만, 배신, 속임수, 도피",
    "keywordsEn": "Deception, betrayal, deceit, escape",
    "description": "기만적인 행동이나 배신에 주의해야 하는 하루입니다. 정직하지 못한 방법으로 무언가를 얻으려 하거나, 반대로 누군가에게 속을 수 있습니다. 정면으로 문제를 마주하는 용기가 필요합니다.",
    "image": "/assets/tarot/swords_7.png",
    "isPositive": false,
    "score": 40,
    "deck": "tarot"
  },
  {
    "id": "swords_8",
    "nameKo": "Eight of Swords",
    "nameEn": "Eight of Swords",
    "keywords": "속박, 제한, 무력감, 자기 억압",
    "keywordsEn": "Bondage, restriction, powerlessness, self-repression",
    "description": "스스로 만든 생각의 감옥에 갇혀 무력감을 느끼는 하루입니다. 상황이 생각만큼 나쁘지 않을 수 있습니다. 부정적인 생각에서 벗어나면 해결책이 보일 것입니다.",
    "image": "/assets/tarot/swords_8.png",
    "isPositive": false,
    "score": 15,
    "deck": "tarot"
  },
  {
    "id": "swords_9",
    "nameKo": "Nine of Swords",
    "nameEn": "Nine of Swords",
    "keywords": "불안, 걱정, 악몽, 절망",
    "keywordsEn": "Anxiety, worry, nightmare, despair",
    "description": "지나친 걱정과 불안감으로 잠 못 이루는 힘든 하루가 될 수 있습니다. 최악의 상황을 상상하며 스스로를 괴롭히고 있을 수 있어요. 걱정의 실체를 파악하고 도움을 구하세요.",
    "image": "/assets/tarot/swords_9.png",
    "isPositive": false,
    "score": 10,
    "deck": "tarot"
  },
  {
    "id": "swords_10",
    "nameKo": "Ten of Swords",
    "nameEn": "Ten of Swords",
    "keywords": "실패, 끝, 절망, 새로운 시작의 여명",
    "keywordsEn": "Failure, end, despair, dawn of new beginning",
    "description": "더 이상 나빠질 수 없는 최악의 상황, 완전한 끝을 마주하는 하루입니다. 하지만 모든 것이 끝난 바로 그 지점에서 새로운 시작이 가능합니다. 바닥을 쳤으니 이제 올라갈 일만 남았습니다.",
    "image": "/assets/tarot/swords_10.png",
    "isPositive": false,
    "score": 5,
    "deck": "tarot"
  },
  {
    "id": "ace_wands",
    "nameKo": "Ace of Wands",
    "nameEn": "Ace of Wands",
    "keywords": "열정, 창의력, 영감, 새로운 시작",
    "keywordsEn": "Passion, creativity, inspiration, new beginning",
    "description": "새로운 열정과 창의적인 에너지가 샘솟는 하루입니다. 새로운 프로젝트를 시작하거나, 당신의 영감을 행동으로 옮기기에 완벽한 날입니다. 망설이지 말고 도전하세요.",
    "image": "/assets/tarot/ace_wands.png",
    "isPositive": true,
    "score": 85,
    "deck": "tarot"
  },
  {
    "id": "wands_2",
    "nameKo": "Two of Wands",
    "nameEn": "Two of Wands",
    "keywords": "미래 계획, 결정, 용기, 확장",
    "keywordsEn": "Future planning, decision, courage, expansion",
    "description": "미래에 대한 계획을 세우고 새로운 가능성을 탐색하는 하루입니다. 현재의 성공에 안주하지 않고 더 큰 세상을 향해 나아갈 준비를 하게 됩니다. 대담한 결정을 내리기에 좋은 날입니다.",
    "image": "/assets/tarot/wands_2.png",
    "isPositive": true,
    "score": 70,
    "deck": "tarot"
  },
  {
    "id": "wands_3",
    "nameKo": "Three of Wands",
    "nameEn": "Three of Wands",
    "keywords": "확장, 성장, 리더십, 미래에 대한 기대",
    "keywordsEn": "Expansion, growth, leadership, expectation for the future",
    "description": "당신의 계획이 순조롭게 진행되고, 노력의 첫 결실을 기대하게 되는 하루입니다. 더 넓은 세상으로 확장해 나갈 기회가 보입니다. 긍정적인 전망을 믿고 계속 나아가세요.",
    "image": "/assets/tarot/wands_3.png",
    "isPositive": true,
    "score": 75,
    "deck": "tarot"
  },
  {
    "id": "wands_4",
    "nameKo": "Four of Wands",
    "nameEn": "Four of Wands",
    "keywords": "축하, 안정, 조화, 행복",
    "keywordsEn": "Celebration, stability, harmony, happiness",
    "description": "안정된 기반 위에서 축하할 일이 생기는 평화롭고 즐거운 하루입니다. 가족, 친구들과 함께 성과를 나누고 행복한 시간을 보내세요. 조화와 안정을 만끽할 수 있는 날입니다.",
    "image": "/assets/tarot/wands_4.png",
    "isPositive": true,
    "score": 65,
    "deck": "tarot"
  },
  {
    "id": "wands_5",
    "nameKo": "Five of Wands",
    "nameEn": "Five of Wands",
    "keywords": "경쟁, 갈등, 의견 충돌, 혼란",
    "keywordsEn": "Competition, conflict, disagreement, chaos",
    "description": "사소한 의견 충돌이나 경쟁으로 인해 시끄러운 하루가 될 수 있습니다. 갈등이 성장을 위한 건전한 자극제가 될 수도 있지만, 불필요한 에너지 소모는 피하는 것이 좋습니다.",
    "image": "/assets/tarot/wands_5.png",
    "isPositive": false,
    "score": 35,
    "deck": "tarot"
  },
  {
    "id": "wands_6",
    "nameKo": "Six of Wands",
    "nameEn": "Six of Wands",
    "keywords": "승리, 성공, 인정, 자신감",
    "keywordsEn": "Victory, success, recognition, confidence",
    "description": "노력의 대가로 대중의 인정과 성공을 거머쥐는 영광스러운 하루입니다. 당신의 승리를 주변 사람들과 함께 축하하세요. 자신감을 갖고 다음 목표를 향해 나아갈 수 있습니다.",
    "image": "/assets/tarot/wands_6.png",
    "isPositive": true,
    "score": 80,
    "deck": "tarot"
  },
  {
    "id": "wands_7",
    "nameKo": "Seven of Wands",
    "nameEn": "Seven of Wands",
    "keywords": "도전, 방어, 용기, 끈기",
    "keywordsEn": "Challenge, defense, courage, perseverance",
    "description": "자신의 신념이나 입장을 지키기 위해 고군분투해야 하는 하루입니다. 많은 도전과 비판에 직면할 수 있지만, 용기를 갖고 맞서 싸운다면 유리한 고지를 지킬 수 있습니다.",
    "image": "/assets/tarot/wands_7.png",
    "isPositive": false,
    "score": 40,
    "deck": "tarot"
  },
  {
    "id": "wands_8",
    "nameKo": "Eight of Wands",
    "nameEn": "Eight of Wands",
    "keywords": "급속한 전개, 소식, 이동, 행동",
    "keywordsEn": "Rapid development, news, movement, action",
    "description": "상황이 매우 빠르게 진행되고, 기다리던 소식이 도착하는 역동적인 하루입니다. 갑작스러운 여행이나 새로운 기회가 찾아올 수 있습니다. 빠른 변화에 맞춰 신속하게 행동하세요.",
    "image": "/assets/tarot/wands_8.png",
    "isPositive": true,
    "score": 75,
    "deck": "tarot"
  },
  {
    "id": "wands_9",
    "nameKo": "Nine of Wands",
    "nameEn": "Nine of Wands",
    "keywords": "인내, 방어, 끈기, 경계",
    "keywordsEn": "Patience, defense, perseverance, boundary",
    "description": "계속되는 싸움에 지쳐있지만, 마지막까지 경계를 늦출 수 없는 하루입니다. 거의 다 왔으니 포기하지 마세요. 당신의 끈기와 인내력이 결국 승리를 가져다줄 것입니다.",
    "image": "/assets/tarot/wands_9.png",
    "isPositive": false,
    "score": 30,
    "deck": "tarot"
  },
  {
    "id": "wands_10",
    "nameKo": "Ten of Wands",
    "nameEn": "Ten of Wands",
    "keywords": "과도한 책임, 부담, 압박감, 번아웃",
    "keywordsEn": "Excessive responsibility, pressure, pressure, burnout",
    "description": "너무 많은 책임과 부담감에 짓눌려 힘든 하루입니다. 혼자 모든 짐을 짊어지려 하지 말고, 다른 사람에게 도움을 요청하거나 일부를 내려놓는 용기가 필요합니다.",
    "image": "/assets/tarot/wands_10.png",
    "isPositive": false,
    "score": 20,
    "deck": "tarot"
  },
  {
    "id": "page_cups",
    "nameKo": "Page of Cups",
    "nameEn": "Page of Cups",
    "keywords": "창의적 영감, 직관적 메시지, 감수성, 호기심",
    "keywordsEn": "Creative inspiration, intuitive message, sensitivity, curiosity",
    "description": "예상치 못한 감정적 메시지나 창의적인 제안을 받게 되는 하루입니다. 당신의 직감을 믿고 마음을 열어두세요. 새로운 관계나 아이디어가 싹틀 수 있습니다.",
    "image": "/assets/tarot/page_cups.png",
    "isPositive": true,
    "score": 70,
    "deck": "tarot"
  },
  {
    "id": "page_pentacles",
    "nameKo": "Page of Pentacles",
    "nameEn": "Page of Pentacles",
    "keywords": "새로운 기회, 학습, 성실함, 현실적인 계획",
    "keywordsEn": "New opportunity, learning, diligence, practical plan",
    "description": "새로운 것을 배우거나 실용적인 기술을 익히기에 좋은 하루입니다. 새로운 사업 기회나 투자 제안이 있을 수 있습니다. 성실한 자세로 임한다면 좋은 결실을 맺을 것입니다.",
    "image": "/assets/tarot/page_pentacles.png",
    "isPositive": true,
    "score": 65,
    "deck": "tarot"
  },
  {
    "id": "page_swords",
    "nameKo": "Page of Swords",
    "nameEn": "Page of Swords",
    "keywords": "새로운 아이디어, 호기심, 진실 탐구, 솔직함",
    "keywordsEn": "New ideas, curiosity, truth pursuit, honesty",
    "description": "새로운 아이디어가 넘치고 지적 호기심이 왕성해지는 하루입니다. 새로운 정보를 탐색하고 진실을 추구하려는 에너지가 강합니다. 성급한 말이나 행동은 주의해야 합니다.",
    "image": "/assets/tarot/page_swords.png",
    "isPositive": true,
    "score": 60,
    "deck": "tarot"
  },
  {
    "id": "page_wands",
    "nameKo": "Page of Wands",
    "nameEn": "Page of Wands",
    "keywords": "새로운 열정, 모험심, 탐험, 긍정적 에너지",
    "keywordsEn": "New passion, adventurous spirit, exploration, positive energy",
    "description": "새로운 모험에 대한 열정이 샘솟고, 탐험하고 싶은 에너지가 가득한 하루입니다. 새로운 가능성을 발견하고 열정적으로 뛰어들 준비가 되었습니다. 자유롭게 자신을 표현하세요.",
    "image": "/assets/tarot/page_wands.png",
    "isPositive": true,
    "score": 75,
    "deck": "tarot"
  },
  {
    "id": "knight_cups",
    "nameKo": "Knight of Cups",
    "nameEn": "Knight of Cups",
    "keywords": "로맨스, 제안, 매력, 감성",
    "keywordsEn": "Romance, proposal, charm, sensitivity",
    "description": "로맨틱한 제안을 받거나, 마음을 사로잡는 사람을 만날 수 있는 하루입니다. 당신의 감정을 따라 움직이세요. 예술적이고 창의적인 활동에서도 좋은 성과를 기대할 수 있습니다.",
    "image": "/assets/tarot/knight_cups.png",
    "isPositive": true,
    "score": 75,
    "deck": "tarot"
  },
  {
    "id": "knight_pentacles",
    "nameKo": "Knight of Pentacles",
    "nameEn": "Knight of Pentacles",
    "keywords": "성실함, 책임감, 꾸준함, 신뢰",
    "keywordsEn": "Diligence, responsibility, consistency, trust",
    "description": "오늘은 목표를 향해 꾸준하고 성실하게 나아가는 것이 중요한 하루입니다. 빠른 결과보다는 신중하고 책임감 있는 태도가 좋은 결실을 가져다줄 것입니다. 신뢰를 쌓기에 좋은 날입니다.",
    "image": "/assets/tarot/knight_pentacles.png",
    "isPositive": true,
    "score": 70,
    "deck": "tarot"
  },
  {
    "id": "knight_swords",
    "nameKo": "Knight of Swords",
    "nameEn": "Knight of Swords",
    "keywords": "성급함, 충동적 행동, 논쟁, 저돌적",
    "keywordsEn": "Haste, impulsive action, argument, stubbornness",
    "description": "목표를 향해 너무 성급하고 저돌적으로 달려나가다 실수를 저지를 수 있는 하루입니다. 야망은 좋지만, 주변 상황을 살피지 않는 충동적인 행동은 갈등을 유발할 수 있으니 주의하세요.",
    "image": "/assets/tarot/knight_swords.png",
    "isPositive": false,
    "score": 45,
    "deck": "tarot"
  },
  {
    "id": "knight_wands",
    "nameKo": "Knight of Wands",
    "nameEn": "Knight of Wands",
    "keywords": "열정, 모험, 자신감, 행동력",
    "keywordsEn": "Passion, adventure, confidence, action",
    "description": "에너지가 넘치고 자신감 있게 행동하는 매력적인 하루입니다. 새로운 모험을 찾아 떠나거나 열정적으로 프로젝트를 추진하게 될 수 있습니다. 당신의 열정이 주변에 긍정적인 영향을 미칩니다.",
    "image": "/assets/tarot/knight_wands.png",
    "isPositive": true,
    "score": 80,
    "deck": "tarot"
  },
  {
    "id": "queen_cups",
    "nameKo": "Queen of Cups",
    "nameEn": "Queen of Cups",
    "keywords": "공감 능력, 직관, 감성적 지혜, 따뜻함",
    "keywordsEn": "Empathy, intuition, emotional wisdom, warmth",
    "description": "오늘은 당신의 뛰어난 직관과 공감 능력이 빛을 발하는 하루입니다. 주변 사람들의 마음을 따뜻하게 보듬어주고 현명한 조언을 해줄 수 있습니다. 당신의 내면의 목소리를 신뢰하세요.",
    "image": "/assets/tarot/queen_cups.png",
    "isPositive": true,
    "score": 85,
    "deck": "tarot"
  },
  {
    "id": "queen_pentacles",
    "nameKo": "Queen of Pentacles",
    "nameEn": "Queen of Pentacles",
    "keywords": "풍요, 안정, 실용성, 보살핌",
    "keywordsEn": "Abundance, stability, practicality, care",
    "description": "현실적이면서도 따뜻한 마음으로 주변을 돌보는 능력이 발휘되는 하루입니다. 일과 가정 모두를 풍요롭게 만들 수 있습니다. 안정되고 편안한 환경을 만드는 데 집중해보세요.",
    "image": "/assets/tarot/queen_pentacles.png",
    "isPositive": true,
    "score": 80,
    "deck": "tarot"
  },
  {
    "id": "queen_swords",
    "nameKo": "Queen of Swords",
    "nameEn": "Queen of Swords",
    "keywords": "독립적, 명확한 판단, 지성, 냉철함",
    "keywordsEn": "Independence, clear judgment, intelligence, coldness",
    "description": "오늘은 예리하고 독립적인 판단력이 돋보이지만, 때로는 너무 차갑고 비판적으로 보일 수 있는 하루입니다. 진실을 추구하는 것은 좋지만, 따뜻한 말 한마디를 잊지 마세요.",
    "image": "/assets/tarot/queen_swords.png",
    "isPositive": false,
    "score": 50,
    "deck": "tarot"
  },
  {
    "id": "queen_wands",
    "nameKo": "Queen of Wands",
    "nameEn": "Queen of Wands",
    "keywords": "자신감, 열정, 매력, 리더십",
    "keywordsEn": "Confidence, enthusiasm, charm, leadership",
    "description": "자신감 넘치고 열정적인 매력을 마음껏 발산하는 하루입니다. 당신의 활기찬 에너지가 주변 사람들에게 영감을 주고, 모든 일을 주도적으로 이끌어 나갈 수 있습니다. 사교 활동에서 빛을 발합니다.",
    "image": "/assets/tarot/queen_wands.png",
    "isPositive": true,
    "score": 86,
    "deck": "tarot"
  },
  {
    "id": "king_cups",
    "nameKo": "King of Cups",
    "nameEn": "King of Cups",
    "keywords": "감정적 균형, 자비, 성숙함, 지혜",
    "keywordsEn": "Emotional balance, mercy, maturity, wisdom",
    "description": "감정적으로 성숙하고 균형 잡힌 태도로 모든 상황을 다루는 하루입니다. 감정에 휘둘리지 않으면서도 타인에게 공감하는 능력이 뛰어납니다. 현명한 조언자 역할을 하게 될 수 있습니다.",
    "image": "/assets/tarot/king_cups.png",
    "isPositive": true,
    "score": 80,
    "deck": "tarot"
  },
  {
    "id": "king_pentacles",
    "nameKo": "King of Pentacles",
    "nameEn": "King of Pentacles",
    "keywords": "사업적 성공, 풍요, 안정, 리더십",
    "keywordsEn": "Business success, abundance, stability, leadership",
    "description": "사업적 수완과 안정적인 리더십으로 풍요와 성공을 이끄는 하루입니다. 당신의 노력이 큰 부와 성취로 돌아옵니다. 믿음직하고 든든한 모습으로 주변의 신뢰를 얻습니다.",
    "image": "/assets/tarot/king_pentacles.png",
    "isPositive": true,
    "score": 85,
    "deck": "tarot"
  },
  {
    "id": "king_swords",
    "nameKo": "King of Swords",
    "nameEn": "King of Swords",
    "keywords": "권위, 지적 능력, 엄격함, 진실",
    "keywordsEn": "Authority, intellectual ability, strictness, truth",
    "description": "지적 권위와 명철한 판단력으로 상황을 지배하는 하루입니다. 하지만 지나치게 엄격하고 냉정한 태도는 주변 사람들에게 상처를 줄 수 있습니다. 권위를 내세우기보다 지혜를 나누세요.",
    "image": "/assets/tarot/king_swords.png",
    "isPositive": false,
    "score": 55,
    "deck": "tarot"
  },
  {
    "id": "king_wands",
    "nameKo": "King of Wands",
    "nameEn": "King of Wands",
    "keywords": "리더십, 비전, 카리스마, 열정",
    "keywordsEn": "Leadership, vision, charisma, passion",
    "description": "타고난 리더십과 카리스마로 비전을 현실로 만드는 강력한 하루입니다. 당신의 창의적인 아이디어와 열정이 많은 사람들을 이끌고 위대한 성공을 이뤄낼 것입니다. 대담하게 행동하세요.",
    "image": "/assets/tarot/king_wands.png",
    "isPositive": true,
    "score": 90,
    "deck": "tarot"
  }
];

export const ORACLE_CARDS = [
  {
    "id": "oracle_1",
    "nameKo": "탄생",
    "nameEn": "탄생",
    "keywords": "탄생",
    "keywordsEn": "탄생",
    "description": "태양의 가호를 받은 태양 카드는 모든 일의 출발과 시작입니다. 될 일은 결코 이루어집니다.",
    "image": "/assets/oracle/01.png",
    "isPositive": true,
    "score": 100,
    "deck": "oracle"
  },
  {
    "id": "oracle_2",
    "nameKo": "상승",
    "nameEn": "상승",
    "keywords": "상승",
    "keywordsEn": "상승",
    "description": "위로 올라가는 상승 카드는 하는 일에 승리가 따를 것을 보여줍니다.",
    "image": "/assets/oracle/02.png",
    "isPositive": true,
    "score": 100,
    "deck": "oracle"
  },
  {
    "id": "oracle_3",
    "nameKo": "명예",
    "nameEn": "명예",
    "keywords": "명예",
    "keywordsEn": "명예",
    "description": "명예 카드는 질문이 곧 나의 명예를 상승시켜 줄 수 있음을 보여줍니다.",
    "image": "/assets/oracle/03.png",
    "isPositive": true,
    "score": 100,
    "deck": "oracle"
  },
  {
    "id": "oracle_4",
    "nameKo": "리더쉽",
    "nameEn": "리더쉽",
    "keywords": "리더쉽",
    "keywordsEn": "리더쉽",
    "description": "리더쉽 카드는 나의 자리가 견고함을 보여줍니다. 질문이 긍정적인 방향으로 갈 것을 알려줍니다.",
    "image": "/assets/oracle/04.png",
    "isPositive": true,
    "score": 84,
    "deck": "oracle"
  },
  {
    "id": "oracle_5",
    "nameKo": "우울",
    "nameEn": "우울",
    "keywords": "우울",
    "keywordsEn": "우울",
    "description": "우울 카드는 고민이 많아지는 것을 보여줍니다. 질문의 방향이 좋지 않은 쪽으로 흘러갈 가능성이 있습니다.",
    "image": "/assets/oracle/05.png",
    "isPositive": false,
    "score": 73,
    "deck": "oracle"
  },
  {
    "id": "oracle_6",
    "nameKo": "변덕/불안정",
    "nameEn": "변덕/불안정",
    "keywords": "변덕/불안정",
    "keywordsEn": "변덕/불안정",
    "description": "변덕 카드는 불안정한 상태를 보여줍니다. 질문의 미래가 불투명해질 수 있습니다.",
    "image": "/assets/oracle/06.png",
    "isPositive": false,
    "score": 86,
    "deck": "oracle"
  },
  {
    "id": "oracle_7",
    "nameKo": "가족",
    "nameEn": "가족",
    "keywords": "가족",
    "keywordsEn": "가족",
    "description": "가족 카드는 든든한 울타리 안에 있음을 보여줍니다. 질문의 미래가 안정적이라고 볼 수 있습니다.",
    "image": "/assets/oracle/07.png",
    "isPositive": true,
    "score": 80,
    "deck": "oracle"
  },
  {
    "id": "oracle_8",
    "nameKo": "엄마",
    "nameEn": "엄마",
    "keywords": "엄마",
    "keywordsEn": "엄마",
    "description": "엄마 카드는 언제나 따뜻하게 품어주는 엄마와 같습니다. 질문이 긍정적인 방향으로 흘러갈 수 있습니다.",
    "image": "/assets/oracle/08.png",
    "isPositive": true,
    "score": 90,
    "deck": "oracle"
  },
  {
    "id": "oracle_9",
    "nameKo": "질병",
    "nameEn": "질병",
    "keywords": "질병",
    "keywordsEn": "질병",
    "description": "질병 카드는 뜻과 같이 일이 진행되지 않음을 보여줍니다. 결과가 좋지 않을 수 있습니다.",
    "image": "/assets/oracle/09.png",
    "isPositive": false,
    "score": 94,
    "deck": "oracle"
  },
  {
    "id": "oracle_10",
    "nameKo": "변화",
    "nameEn": "변화",
    "keywords": "변화",
    "keywordsEn": "변화",
    "description": "변화 카드는 변화를 암시합니다. 변화는 잘 대응하면 긍정적이지만 대체로 부정적입니다.",
    "image": "/assets/oracle/10.png",
    "isPositive": false,
    "score": 56,
    "deck": "oracle"
  },
  {
    "id": "oracle_11",
    "nameKo": "지성",
    "nameEn": "지성",
    "keywords": "지성",
    "keywordsEn": "지성",
    "description": "지성 카드는 꽤 긍정적입니다. 지성을 발휘하여 문제를 해결해 나갈 수 있습니다.",
    "image": "/assets/oracle/11.png",
    "isPositive": true,
    "score": 73,
    "deck": "oracle"
  },
  {
    "id": "oracle_12",
    "nameKo": "도둑질",
    "nameEn": "도둑질",
    "keywords": "도둑질",
    "keywordsEn": "도둑질",
    "description": "도둑질 카드는 부정적인 카드입니다. 내 생각과 다르게 타인의 부정 행위에 의해 좌절될 수 있습니다.",
    "image": "/assets/oracle/12.png",
    "isPositive": false,
    "score": 95,
    "deck": "oracle"
  },
  {
    "id": "oracle_13",
    "nameKo": "거래",
    "nameEn": "거래",
    "keywords": "거래",
    "keywordsEn": "거래",
    "description": "트레이드 카드는 꽤 긍정적입니다. 협상이 발생할 수 있지만 긍정적인 쪽으로 타협할 수 있습니다.",
    "image": "/assets/oracle/13.png",
    "isPositive": true,
    "score": 64,
    "deck": "oracle"
  },
  {
    "id": "oracle_14",
    "nameKo": "즐거움",
    "nameEn": "즐거움",
    "keywords": "즐거움",
    "keywordsEn": "즐거움",
    "description": "즐거움 카드는 상당히 긍정적입니다. 결과가 어찌되든 자신이 느끼는 행복과 즐거움이 따릅니다.",
    "image": "/assets/oracle/14.png",
    "isPositive": true,
    "score": 82,
    "deck": "oracle"
  },
  {
    "id": "oracle_15",
    "nameKo": "평화",
    "nameEn": "평화",
    "keywords": "평화",
    "keywordsEn": "평화",
    "description": "평화 카드는 무척 긍정적입니다. 결과는 결국 긍정적인 방향으로 종결되고 평화가 찾아올 것입니다.",
    "image": "/assets/oracle/15.png",
    "isPositive": true,
    "score": 100,
    "deck": "oracle"
  },
  {
    "id": "oracle_16",
    "nameKo": "돈",
    "nameEn": "돈",
    "keywords": "돈",
    "keywordsEn": "돈",
    "description": "돈 카드는 긍정에 가깝습니다. 금전적으로 해결되는 일, 혹은 금전이 되어 돌아오는 일 생길 수 있습니다.",
    "image": "/assets/oracle/16.png",
    "isPositive": true,
    "score": 88,
    "deck": "oracle"
  },
  {
    "id": "oracle_17",
    "nameKo": "사랑",
    "nameEn": "사랑",
    "keywords": "사랑",
    "keywordsEn": "사랑",
    "description": "사랑 카드는 긍정입니다. 연애와 관련한 질문이었다면 결국 사랑의 화합으로 이어질 것입니다.",
    "image": "/assets/oracle/17.png",
    "isPositive": true,
    "score": 100,
    "deck": "oracle"
  },
  {
    "id": "oracle_18",
    "nameKo": "음식과 음료",
    "nameEn": "음식과 음료",
    "keywords": "음식과 음료",
    "keywordsEn": "음식과 음료",
    "description": "음식과 음료 카드는 긍정입니다. 맛있는걸 먹고 마시며 즐거운 시간으로 이어질 것입니다.",
    "image": "/assets/oracle/18.png",
    "isPositive": true,
    "score": 88,
    "deck": "oracle"
  },
  {
    "id": "oracle_19",
    "nameKo": "악의",
    "nameEn": "악의",
    "keywords": "악의",
    "keywordsEn": "악의",
    "description": "악의 카드는 부정적입니다. 내 뜻과 달리 타인의 개입이나 악의로 인해 좌절될 수 있습니다.",
    "image": "/assets/oracle/19.png",
    "isPositive": false,
    "score": 100,
    "deck": "oracle"
  },
  {
    "id": "oracle_20",
    "nameKo": "전쟁",
    "nameEn": "전쟁",
    "keywords": "전쟁",
    "keywordsEn": "전쟁",
    "description": "전쟁 카드는 부정적입니다. 서로 충돌하고 싸우고 오해하는 일이 생길 수 있습니다.",
    "image": "/assets/oracle/20.png",
    "isPositive": false,
    "score": 100,
    "deck": "oracle"
  },
  {
    "id": "oracle_21",
    "nameKo": "적",
    "nameEn": "적",
    "keywords": "적",
    "keywordsEn": "적",
    "description": "적 카드는 부정적입니다. 나를 해치고 음해하는 적이 가까운 곳에 있을 수 있습니다.",
    "image": "/assets/oracle/21.png",
    "isPositive": false,
    "score": 100,
    "deck": "oracle"
  },
  {
    "id": "oracle_22",
    "nameKo": "불/재난",
    "nameEn": "불/재난",
    "keywords": "불/재난",
    "keywordsEn": "불/재난",
    "description": "재난 카드는 부정적입니다. 내 뜻과 다른 재해와 가까운 외부 변수로 인해 좌절될 수 있습니다.",
    "image": "/assets/oracle/22.png",
    "isPositive": false,
    "score": 100,
    "deck": "oracle"
  },
  {
    "id": "oracle_23",
    "nameKo": "사고",
    "nameEn": "사고",
    "keywords": "사고",
    "keywordsEn": "사고",
    "description": "사고 카드는 부정적입니다. 갑작스러운 이슈가 생길 수 있습니다.",
    "image": "/assets/oracle/23.png",
    "isPositive": false,
    "score": 100,
    "deck": "oracle"
  },
  {
    "id": "oracle_24",
    "nameKo": "지원/후원",
    "nameEn": "지원/후원",
    "keywords": "지원/후원",
    "keywordsEn": "지원/후원",
    "description": "성찰 카드는 긍정적입니다. 자아 성찰을 통해 더 나은 미래로 나아갈 수 있습니다.",
    "image": "/assets/oracle/24.png",
    "isPositive": true,
    "score": 70,
    "deck": "oracle"
  },
  {
    "id": "oracle_25",
    "nameKo": "좋은 기회",
    "nameEn": "좋은 기회",
    "keywords": "좋은 기회",
    "keywordsEn": "좋은 기회",
    "description": "좋은 기회 카드는 무척 긍정적입니다. 생각하지 못한 좋은 기회가 가까운 곳에서 기다리고 있을 수 있습니다.",
    "image": "/assets/oracle/25.png",
    "isPositive": true,
    "score": 100,
    "deck": "oracle"
  },
  {
    "id": "oracle_26",
    "nameKo": "명성",
    "nameEn": "명성",
    "keywords": "명성",
    "keywordsEn": "명성",
    "description": "명성 카드는 무척 긍정적입니다. 주변에 나의 좋은 소식, 명성이 올라가는 긍정적인 이벤트가 있을 수 있습니다.",
    "image": "/assets/oracle/26.png",
    "isPositive": true,
    "score": 100,
    "deck": "oracle"
  },
  {
    "id": "oracle_27",
    "nameKo": "불운",
    "nameEn": "불운",
    "keywords": "불운",
    "keywordsEn": "불운",
    "description": "불운 카드는 부정적입니다. 내 실수나 잘못을 떠나서 찾아오는 불운이 생길 수 있습니다.",
    "image": "/assets/oracle/27.png",
    "isPositive": false,
    "score": 100,
    "deck": "oracle"
  },
  {
    "id": "oracle_28",
    "nameKo": "비극",
    "nameEn": "비극",
    "keywords": "비극",
    "keywordsEn": "비극",
    "description": "비극 카드는 부정적입니다. 이름에서 느껴지듯 비극적인 결론으로 이어질 수 있으니 주의가 필요합니다.",
    "image": "/assets/oracle/28.png",
    "isPositive": false,
    "score": 100,
    "deck": "oracle"
  },
  {
    "id": "oracle_29",
    "nameKo": "파멸",
    "nameEn": "파멸",
    "keywords": "파멸",
    "keywordsEn": "파멸",
    "description": "파멸 카드는 부정적입니다. 이름에서 느껴지듯 파멸로 향하며 끝날 수 있습니다.",
    "image": "/assets/oracle/29.png",
    "isPositive": false,
    "score": 100,
    "deck": "oracle"
  },
  {
    "id": "oracle_30",
    "nameKo": "지연/고통",
    "nameEn": "지연/고통",
    "keywords": "지연/고통",
    "keywordsEn": "지연/고통",
    "description": "지연 카드는 꽤 부정적입니다. 일의 지연과 막힘이 있을 수 있습니다.",
    "image": "/assets/oracle/30.png",
    "isPositive": false,
    "score": 60,
    "deck": "oracle"
  },
  {
    "id": "oracle_31",
    "nameKo": "고립",
    "nameEn": "고립",
    "keywords": "고립",
    "keywordsEn": "고립",
    "description": "고립 카드는 꽤 부정적입니다. 혼자 고립되어 외롭고 고독한 시간을 보낼 수 있습니다.",
    "image": "/assets/oracle/31.png",
    "isPositive": false,
    "score": 70,
    "deck": "oracle"
  },
  {
    "id": "oracle_32",
    "nameKo": "대화/유머",
    "nameEn": "대화/유머",
    "keywords": "대화/유머",
    "keywordsEn": "대화/유머",
    "description": "유머 카드는 꽤 긍정적입니다. 누군가와 즐겁게 대화하고 웃을 수 있는 시간이 있을 수 있습니다.",
    "image": "/assets/oracle/32.png",
    "isPositive": true,
    "score": 80,
    "deck": "oracle"
  },
  {
    "id": "oracle_33",
    "nameKo": "지혜",
    "nameEn": "지혜",
    "keywords": "지혜",
    "keywordsEn": "지혜",
    "description": "지혜 카드는 지혜로 어려움이나 난관을 헤쳐나갈 수 있음을 보여줍니다. 긍정적입니다.",
    "image": "/assets/oracle/33.png",
    "isPositive": true,
    "score": 89,
    "deck": "oracle"
  },
  {
    "id": "oracle_34",
    "nameKo": "행복",
    "nameEn": "행복",
    "keywords": "행복",
    "keywordsEn": "행복",
    "description": "행복 카드는 곧 행복의 감정이 찾아올 것을 보여줍니다. 행복은 멀리 있지 않습니다.",
    "image": "/assets/oracle/34.png",
    "isPositive": true,
    "score": 100,
    "deck": "oracle"
  },
  {
    "id": "oracle_35",
    "nameKo": "건강한 가치관",
    "nameEn": "건강한 가치관",
    "keywords": "건강한 가치관",
    "keywordsEn": "건강한 가치관",
    "description": "마음 깊이 자리 잡은 건강한 가치관으로 어려움을 이겨내고 극복할 수 있음을 보여줍니다. 무척 긍정적입니다.",
    "image": "/assets/oracle/35.png",
    "isPositive": true,
    "score": 84,
    "deck": "oracle"
  }
];

export function randomCard(deck) {
  const list = deck === "oracle" ? ORACLE_CARDS : TAROT_CARDS;
  return list[Math.floor(Math.random() * list.length)];
}
